### ISSUE TITLE
ArrayIndexOutOfException when the input expression is greater than 8192 Characters.

### ISSUE THREAD

**Issue by ironhide0396** [phax/ParserGeneratorCC#33]

**Comment by phax** [comment]
A little more input would be appreciated. What version are you using? What configuration are you using?

**Comment by ironhide0396** [comment]
@phax Any update on this issue ?

**Comment by jhargraveiii** [comment]
I'm having a similar issue. Any input that has a token size > buffer will crash. in our case this is json values that hold large embedded HTML snippets. Is there an option for this?

**Comment by phax** [comment]
@jhargraveiii can you please PM me the grammar so I can debug into it? See the pom.xml for my email address. Thx

**Comment by phax** [comment]
@jhargraveiii go ahead - a PR is always welcome :)

**Comment by jhargraveiii** [comment]
I've tracked down the issue to "JAVA_UNICODE_ESCAPE=true;". JavaCharStream isn't allocating enough buffer to accommodate large tokens. CharStream works without issue. I'll dig some more.

**Comment by phax** [comment]
@jhargraveiii  see also #26  for some infos

**Comment by jhargraveiii** [comment]
I haven't had time to complete a patch - changes are needed in the 
template to better support buffering for  unicode escape processing.

Jim

**Comment by phax** [comment]
Thank Jim - take your time here. Same issue - lack of time :(

**Comment by opeongo** [comment]
Just chiming in here that I am experiencing the same issue using ParserGeneratorCC in BeanShell.  BeanShell is using ph-javacc-maven-plugin 4.1.5.

I have a large string token (about 20K in length) that is in an assignment statement:
```java
curveLuB10 = "lookupTable(getVa.... blah blah blah";
```

Here is the traceback.  Hopefully this will help even without the grammar:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4096 out of bounds for length 4096
	at bsh.JavaCharStream.readByte(JavaCharStream.java:94)
	at bsh.JavaCharStream.readChar(JavaCharStream.java:137)
	at bsh.ParserTokenManager.jjMoveNfa_0(ParserTokenManager.java:2032)
	at bsh.ParserTokenManager.jjMoveStringLiteralDfa0_0(ParserTokenManager.java:298)
	at bsh.ParserTokenManager.getNextToken(ParserTokenManager.java:2176)
	at bsh.Parser.getToken(Parser.java:7895)
	at bsh.Parser.jjtreeOpenNodeScope(Parser.java:66)
	at bsh.Parser.Expression(Parser.java:1397)
	at bsh.Parser.Expression(Parser.java:1425)
	at bsh.Parser.StatementExpression(Parser.java:3663)
	at bsh.Parser.Statement(Parser.java:3443)
	at bsh.Parser.BlockStatement(Parser.java:3612)
	at bsh.Parser.Line(Parser.java:224)
	at bsh.Interpreter.readLine(Interpreter.java:1048)
	at bsh.Interpreter.eval(Interpreter.java:722)
```

I had a look at what was going on.  The problem seems to start prior to this traceback.  The `JavaCharStream.readChar()` method is called with the `bufferPos == available` (4096 == 4096) and the `AbstractCharStream.internalAdjustBufferSize()` method is called.  The `buffer`, `m_aBufLine` and `aBufColumn` arrays are increased to 8192.  `nPreservedChars` is set to 4081 because the beginning of the current token (the string) is at position 15.  The contents of the old buffers are shifted down by 15 and 4081 values are copied to the new buffers.  `bufpos` and `maxNextCharInd` are set to 4081.  The `AbstractCharStream.internalAdjustBufferSize()` returns.

Next `JavaCharStream.readByte()` is called and this is where the error occurs.  This seems to be using a different buffer (`m_aNextCharBuf`) than the AbstractCharStream class.  The `nextCharInd` value is 4095 which immediately gets incremented to 4096.  `JavaCharStream.fillBuff()` is called.  Since `maxNextCharInd` is 4081 another 15 characters are read to the end of the buffer.  But the `nextCharInd` value is not changed from 4096.  The `JavaCharStream.fillBuff()` routine returns, and `JavaCharStream.readByte` tries to read a value at position `nextCharInd` (4096) and the error occurs.

I cannot follow the complete logic here, but it seems that the buffer expansion method in the AbstractCharStream super class is not doing a proper job of updating the buffer positions that are actually being used in the JavaCharStream class.  In fact if I comment out the lines at [here](https://github.com/tulipcc/ParserGeneratorCC/blob/53c1ca3beb97a2ee4679ff4e19d192eec5a6990e/src/main/resources/templates/stream/java/AbstractCharStream.template#L199) and [here](https://github.com/tulipcc/ParserGeneratorCC/blob/53c1ca3beb97a2ee4679ff4e19d192eec5a6990e/src/main/resources/templates/stream/java/AbstractCharStream.template#L217) the problem seems to go away.

Can you have a look and confirm if my change is doing the right thing?  

Also, If I want to persist this change in to BeanShell is there a way to do it by just editing the output AbstractCharStream.java and preventing Maven from overwriting it?

**Comment by jhargraveiii** [comment]
Yeah we are still stuck on an old version to avoid this problem. I tried 
to fix it way back when - the logic that adjusts the buffer size needs 
to be updated for the JavaCharStream. We use that stream to get support 
for escaped Unicode sequences.

Jim

**Comment by opeongo** [comment]
@jhargraveiii Can you try the fix that I suggested and see if it solves the problem for you?  That way we will have another data point in trying to track down this issue.

Tom

**Comment by jhargraveiii** [comment]
Hey Tom - would be happy to do that. Do you have a modified branch I can 
use?

Jim

**Comment by jhargraveiii** [comment]
So I just decided to switch to https://www.mojohaus.org/javacc-maven-plugin/

It doesn't depend on a JavaCC fork. I like the changes in the fork - but 
the author just doesn't have time to give it fixes and updates.

Jim

**Comment by phax** [comment]
Yes, the particular fix really doesn't look "straight forward" so I think there must be kind of a simpler solution than shuffling with a list of list of chars ....
